# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.100.2"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 512
    vb.cpus = 2
    vb.name = "ubuntu"
  end

  config.vm.hostname = "ubuntu"

  config.vm.provision "shell", path: "provision.sh"
end

