# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.3.65"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = 512
    vb.cpus = 2
    vb.name = "ubuntu"
  end

  config.vm.hostname = "ubuntu"
  
  config.vm.provision "shell", path: "provision.sh"
end

