# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-11.0-STABLE"

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.3.66"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 512
    vb.cpus = 2
    vb.name = "freebsd"
  end

  config.vm.hostname = "freebsd"

end
